// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jackson API Support",
            "email": "Jacksontpa7@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/category/create-category": {
            "post": {
                "description": "Create Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create Category",
                "parameters": [
                    {
                        "description": "Category Name",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/category/get-all-category": {
            "get": {
                "description": "Retrieve all categories from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get all categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Category"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/highlight/by-streamer-id": {
            "get": {
                "description": "Get Highlight by StreamerID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video Highlight"
                ],
                "summary": "Get Highlight by StreamerID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Streamer ID",
                        "name": "streamerID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateHighlightResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/highlight/create": {
            "post": {
                "description": "Create Video Highlight",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video Highlight"
                ],
                "summary": "Create Video Highlight",
                "parameters": [
                    {
                        "description": "highlight",
                        "name": "highlight",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateHighlightRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateHighlightResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/messages/{stream_id}": {
            "get": {
                "description": "Retrieve all chat messages by Stream ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Get all messages for a stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream ID",
                        "name": "stream_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Message"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream-history/all-stream": {
            "get": {
                "description": "Get all stream history by streamerID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream History"
                ],
                "summary": "Get all stream history by streamerID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host Principal ID",
                        "name": "hostPrincipalID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.StreamHistoryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream-history/by-id": {
            "get": {
                "description": "Get stream history by streamHistoryID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream History"
                ],
                "summary": "Get stream history by streamHistoryID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream History ID",
                        "name": "streamHistoryID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream-history/create": {
            "post": {
                "description": "Create Stream History",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream History"
                ],
                "summary": "Create Stream History",
                "parameters": [
                    {
                        "description": "Stream History",
                        "name": "CreateStreamHistory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateStreamHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateStreamHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream-info/": {
            "put": {
                "description": "Create or update stream info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StreamInfo"
                ],
                "summary": "Create or update stream info",
                "parameters": [
                    {
                        "description": "DTO",
                        "name": "dto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateStreamInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream-info/{hostPrincipalID}": {
            "get": {
                "description": "get stream info by user id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StreamInfo"
                ],
                "summary": "get stream info by user id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host Principal ID",
                        "name": "hostPrincipalID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/streams/all-active-stream": {
            "get": {
                "description": "Get all active stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Get all active stream",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.StreamResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/streams/by-stream-id": {
            "get": {
                "description": "Get active stream by streamID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Get active stream by streamID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream ID",
                        "name": "streamID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/streams/by-streamer-id": {
            "get": {
                "description": "Get active stream by streamerID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Get active stream by streamerID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Streamer ID",
                        "name": "streamerID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/streams/create-stream": {
            "post": {
                "description": "Create Stream with thumbnail upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Create Stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host Principal ID",
                        "name": "hostPrincipalId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stream title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stream Category ID",
                        "name": "streamCategoryId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail file",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateStreamingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/streams/stop-stream": {
            "post": {
                "description": "Stop active stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Stop active stream",
                "parameters": [
                    {
                        "description": "DTO",
                        "name": "dto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateStreamActiveStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/viewer-history/create": {
            "post": {
                "description": "Create Viewer History",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Viewer History"
                ],
                "summary": "Create Viewer History",
                "parameters": [
                    {
                        "description": "Viewer History",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateViewerHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateViewerHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ClipRequest": {
            "type": "object",
            "properties": {
                "endHighlight": {
                    "type": "string",
                    "example": "0.5"
                },
                "highlightDescription": {
                    "type": "string",
                    "example": "hello world"
                },
                "highlightStreamHistoryID": {
                    "type": "string",
                    "example": "streamhistory123"
                },
                "highlightUrl": {
                    "type": "string",
                    "example": "url123"
                },
                "startHighlight": {
                    "type": "string",
                    "example": "0.0"
                }
            }
        },
        "dtos.ClipResponse": {
            "type": "object",
            "properties": {
                "endHighlight": {
                    "type": "string"
                },
                "highlightDescription": {
                    "type": "string"
                },
                "highlightID": {
                    "type": "string"
                },
                "highlightStreamHistoryID": {
                    "type": "string"
                },
                "highlightUrl": {
                    "type": "string"
                },
                "startHighlight": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateCategoryRequest": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string",
                    "example": "RPG"
                }
            }
        },
        "dtos.CreateHighlightRequest": {
            "type": "object",
            "properties": {
                "clips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ClipRequest"
                    }
                }
            }
        },
        "dtos.CreateHighlightResponse": {
            "type": "object",
            "properties": {
                "highlights": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ClipResponse"
                    }
                }
            }
        },
        "dtos.CreateStreamHistoryRequest": {
            "type": "object",
            "properties": {
                "hostPrincipalID": {
                    "type": "string",
                    "example": "user123"
                },
                "streamID": {
                    "type": "string",
                    "example": "stream123"
                },
                "videoUrl": {
                    "type": "string",
                    "example": "supabase storage video"
                }
            }
        },
        "dtos.CreateStreamHistoryResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "hostPrincipalId": {
                    "type": "string"
                },
                "streamHistoryId": {
                    "type": "string"
                },
                "streamHistoryStreamId": {
                    "type": "string"
                },
                "videoUrl": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateStreamInfoRequest": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string",
                    "example": "123"
                },
                "hostPrincipalId": {
                    "type": "string",
                    "example": "123"
                },
                "title": {
                    "type": "string",
                    "example": "My First Stream!!"
                }
            }
        },
        "dtos.CreateStreamingResponse": {
            "type": "object",
            "properties": {
                "createAt": {
                    "type": "string"
                },
                "hostPrincipalId": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "streamCategoryName": {
                    "type": "string"
                },
                "streamId": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateViewerHistoryRequest": {
            "type": "object",
            "properties": {
                "viewerHistoryPrincipalID": {
                    "type": "string",
                    "example": "user123"
                },
                "viewerHistoryStreamHistoryID": {
                    "type": "string",
                    "example": "stream123"
                }
            }
        },
        "dtos.CreateViewerHistoryResponse": {
            "type": "object",
            "properties": {
                "viewerHistoryID": {
                    "type": "string"
                },
                "viewerHistoryPrincipalID": {
                    "type": "string"
                },
                "viewerHistoryStreamHistoryID": {
                    "type": "string"
                }
            }
        },
        "dtos.MessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "messageID": {
                    "type": "string"
                },
                "senderID": {
                    "type": "string"
                }
            }
        },
        "dtos.StreamHistoryResponse": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "hostPrincipalID": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.MessageResponse"
                    }
                },
                "streamHistoryID": {
                    "type": "string"
                },
                "streamHistoryStreamID": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalView": {
                    "type": "integer"
                },
                "videoUrl": {
                    "type": "string"
                }
            }
        },
        "dtos.StreamInfoResponse": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string"
                },
                "hostPrincipalId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtos.StreamResponse": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "hostPrincipalID": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.MessageResponse"
                    }
                },
                "streamId": {
                    "type": "string"
                },
                "thumbnailURL": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "viewerCount": {
                    "type": "integer"
                }
            }
        },
        "dtos.UpdateStreamActiveStatusRequest": {
            "type": "object",
            "properties": {
                "hostPrincipalId": {
                    "type": "string",
                    "example": "stream123"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "string"
                },
                "categoryName": {
                    "type": "string"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "messageID": {
                    "type": "string"
                },
                "messagePrincipalID": {
                    "type": "string"
                },
                "streamID": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Streaming Backend API",
	Description:      "API documentation for the streaming live chat backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
